steps:
  - id: "tf-init"
    name: "hashicorp/terraform:1.15.8"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd development/environments/${_ENV}
        terraform init

  - id: ""



substitutions:
  _ENV: "dev"

options:
  logging: CLOUD_LOGGING_ONLY